name: Build GMpro2 v5.6

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Update ke v4 biar aman

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP8266 Core 2.0.0
        run: |
          arduino-cli config init
          arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266@2.0.0 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Compile
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --output-dir ./build ./GMpro2_Final_v56.ino

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # INI KUNCINYA NYET, GANTI V3 KE V4
        with:
          name: M1Z23R_BIN_FINAL
          path: ./build/*.bin
